export type ContentSection = { heading: string; body: string };
export type Faq = { question: string; answer: string };
export type SearchPage = {
  slug: string;
  title: string;
  metaTitle: string;
  description: string;
  intro: string;
  sections: ContentSection[];
  faqs: Faq[];
  related: { label: string; href: string }[];
};
export type Article = SearchPage & { published: string; category: string };

export const features: SearchPage[] = [
  {
    slug: "sales-management", title: "Sales management for busy Tanzanian shops", metaTitle: "Sales Management Software for Shops in Tanzania", description: "Record paid and credit sales, keep a clear transaction history, and see daily sales totals with DukaSmart shop sales software.", intro: "A useful sales record should take less time than searching through a notebook at closing. DukaSmart gives shop owners and counter staff one place to record each sale and understand what the business has sold.",
    sections: [
      { heading: "Record the sale while it happens", body: "Choose products, enter quantities, and record whether the customer paid or bought on credit. DukaSmart uses the product's current selling price and reduces stock as part of the same transaction, helping keep sales and inventory in step." },
      { heading: "Know what sold today", body: "The owner dashboard summarizes today's sales and the month's activity. Recent transactions and product-level sales reports make it easier to review activity without adding up separate pages in a book." },
      { heading: "Keep the counter workflow simple", body: "The sales screen works on a phone, tablet, or computer. Employees can record sales for their shop, while owner-only dashboard and reporting areas remain restricted to the owner role." },
    ],
    faqs: [{ question: "Can I record a sale that has not been paid in full?", answer: "Yes. Choose credit as the payment status and optionally save the customer's name and phone number." }, { question: "Does recording a sale change stock?", answer: "Yes. Product quantities are checked and reduced within the sale transaction, and a sale that exceeds available stock is rejected." }],
    related: [{ label: "Credit sales tracking", href: "/features/credit-sales" }, { label: "Inventory management", href: "/features/inventory-management" }, { label: "Sales and profit reports", href: "/features/business-reports" }],
  },
  {
    slug: "inventory-management", title: "Inventory management that keeps your shop in view", metaTitle: "Inventory Management System for Shops in Tanzania", description: "Track product quantities, costs, selling prices, and low-stock points with practical inventory management software for Tanzanian shops.", intro: "When stock is scattered across shelves and handwritten notes, it is hard to know what is available or what needs reordering. DukaSmart connects product records to the sales and purchase activity that changes them.",
    sections: [
      { heading: "Build a dependable product list", body: "Give each product a name, category, unit, cost price, selling price, quantity, and low-stock threshold. This gives the team a shared reference instead of relying on one person's memory." },
      { heading: "Let activity update quantities", body: "Recorded sales reduce on-hand stock. Recorded purchases add received quantities and update the latest unit cost. That connection helps owners spot differences between what the system says and what they count on the shelf." },
      { heading: "See what needs attention", body: "Set a low-stock threshold for each item and review the alert list when planning a restock. The threshold is a prompt for a decision, not an automatic order, so you can account for supplier lead times and seasonal demand." },
    ],
    faqs: [{ question: "Can I set different reorder alerts for each product?", answer: "Yes. Each product has its own low-stock threshold, which you can set based on how quickly that item sells and how long replenishment takes." }, { question: "Can I track stock on a phone?", answer: "Yes. The product list and stock workflows are responsive and work in a mobile browser." }],
    related: [{ label: "Purchase management", href: "/features/purchase-management" }, { label: "Stock reorder calculator", href: "/tools/stock-calculator" }, { label: "Hardware shop workflow", href: "/solutions/hardware-shops" }],
  },
  {
    slug: "purchase-management", title: "Purchase tracking for better restocking decisions", metaTitle: "Purchase Tracking Software for Small Shops", description: "Record supplier purchases, quantities, and unit costs while updating inventory in one workflow with DukaSmart.", intro: "Restocking affects both cash and the amount of stock available to sell. Keeping each delivery's quantities and costs together gives a shop owner a clearer history of what came in and what it cost.",
    sections: [{ heading: "Record what arrived", body: "Create a purchase with the supplier name, products received, quantities, and unit costs. The record gives the owner and staff a consistent way to document incoming stock." }, { heading: "Update stock and current cost", body: "When a purchase is saved, received quantities are added to the relevant product stock. The product's cost price moves to the newly recorded unit cost, while completed sales retain their original cost for historical profit estimates." }, { heading: "Use alerts to plan, not guess", body: "Combine purchase history with product low-stock alerts to decide what to order next. Check supplier availability, delivery timing, and cash flow before placing the order." }],
    faqs: [{ question: "Can a purchase include several products?", answer: "Yes. A purchase can record multiple products and quantities in one transaction." }, { question: "Does a purchase increase my stock?", answer: "Yes. The quantities received are added to each product's on-hand stock when the purchase is recorded." }],
    related: [{ label: "Inventory management", href: "/features/inventory-management" }, { label: "Stock reorder calculator", href: "/tools/stock-calculator" }, { label: "Hardware shop workflow", href: "/solutions/hardware-shops" }],
  },
  {
    slug: "credit-sales", title: "Track credit sales without losing the details", metaTitle: "Credit Sales Tracking for Shops", description: "Record shop credit sales with customer details and review outstanding credit totals in DukaSmart sales reports.", intro: "Credit can be part of serving regular customers, but informal promises are difficult to reconcile later. A consistent transaction record helps a shop know what was sold on credit and which customer details were recorded.",
    sections: [{ heading: "Mark the payment status clearly", body: "Choose credit instead of paid when recording the sale. DukaSmart keeps that status with the sale so it is distinguishable from cash or already-paid transactions." }, { heading: "Keep useful customer context", body: "Add a customer's name and phone number when appropriate. Confirm the details with the customer and follow your own process for due dates and collection; DukaSmart records the sale but does not send payment reminders." }, { heading: "Review credit alongside sales", body: "Owner reports include outstanding credit totals, helping you include unpaid sales in a regular review of shop performance and cash collection." }],
    faqs: [{ question: "Does DukaSmart collect payments automatically?", answer: "No. It records whether a sale is paid or credit; the shop and customer arrange payment directly." }, { question: "Can I include customer contact details?", answer: "Yes. You can optionally enter a customer name and phone number on a sale. Only record information you need and handle it responsibly." }],
    related: [{ label: "Sales management", href: "/features/sales-management" }, { label: "Business reports", href: "/features/business-reports" }, { label: "How to track credit sales", href: "/blog/track-credit-sales-in-a-duka" }],
  },
  {
    slug: "business-reports", title: "Shop sales and profit reports you can act on", metaTitle: "Sales and Profit Reports for Small Shops", description: "Review daily and monthly sales, estimated profit, top products, and outstanding credit in one shop reporting dashboard.", intro: "Reports are useful when they answer everyday questions: what sold, how much came in, and which products need attention? DukaSmart turns recorded shop activity into daily and monthly summaries.",
    sections: [{ heading: "See the shape of recent sales", body: "Review daily totals and a 14-day sales chart, alongside this month's sales count and revenue. Consistent records make it easier to compare periods and notice changes worth investigating." }, { heading: "Understand estimated gross profit", body: "DukaSmart estimates product-level profit from the sale price and cost recorded for each item. This is not net profit: it does not subtract rent, wages, tax, payment fees, or other operating costs." }, { heading: "Export reports for your records", body: "Daily and monthly reports can be exported for further review. Use them as operational summaries and consult a qualified accountant for statutory or tax reporting requirements." }],
    faqs: [{ question: "Is the profit figure the same as take-home profit?", answer: "No. It is an estimate of gross product profit before operating expenses, taxes, and other costs." }, { question: "Who can view business reports?", answer: "Dashboard and reports are owner-only areas. Employees can record sales and purchases but do not have access to owner reports." }],
    related: [{ label: "Sales management", href: "/features/sales-management" }, { label: "Credit sales tracking", href: "/features/credit-sales" }, { label: "Profit calculator", href: "/tools/profit-calculator" }],
  },
];

export const solutions: SearchPage[] = [
  {
    slug: "hardware-shops", title: "Stock and sales management for hardware shops", metaTitle: "Hardware Shop Management Software in Tanzania", description: "Manage building materials, tools, fasteners, sales, purchases, and low-stock alerts with DukaSmart for hardware shops.", intro: "A hardware shop can carry hundreds of products sold in different units, from cement bags and paint tins to individual screws. DukaSmart gives the team one shared product and transaction record.",
    sections: [{ heading: "Keep varied product units organized", body: "Set the unit that makes sense for each item, such as a bag, sheet, tin, kilogram, or piece. Store a cost price, selling price, stock count, and alert threshold with each product." }, { heading: "Record counter sales as they happen", body: "Select products and quantities for a sale. The system checks stock and updates it with the transaction, helping reduce the gap between counter activity and the inventory list." }, { heading: "Plan replenishment from low-stock items", body: "Review threshold alerts before calling suppliers. Pair the alert list with what you know about delivery timing and construction demand; the software supports the decision but does not place orders automatically." }],
    faqs: [{ question: "Can I record products sold in different units?", answer: "Yes. Product records include a unit field, so a shop can identify items by units such as bags, sheets, tins, or pieces." }, { question: "Does it track supplier purchases too?", answer: "Yes. Record received products, quantities, supplier, and unit costs to update stock and keep a purchase history." }],
    related: [{ label: "Inventory management", href: "/features/inventory-management" }, { label: "Purchase tracking", href: "/features/purchase-management" }, { label: "Stock reorder calculator", href: "/tools/stock-calculator" }],
  },
  {
    slug: "mini-supermarkets", title: "A clearer daily workflow for mini supermarkets", metaTitle: "Shop Management Software for Mini Supermarkets", description: "Give mini-market teams a shared way to record sales, monitor fast-moving stock, and review purchases with DukaSmart.", intro: "A mini supermarket needs a reliable view of many everyday products moving through the till and onto shelves. DukaSmart is a lightweight browser-based workspace for maintaining product, sale, and purchase records.",
    sections: [{ heading: "Maintain one product list", body: "Keep names, categories, units, prices, stock, and low-stock thresholds together. Consistent naming helps staff select the right item and owners review what needs replenishing." }, { heading: "Capture sales and stock movement", body: "Record each sale against products and quantities. Stock updates in the same transaction, so a successful sale and the inventory count remain connected." }, { heading: "Review fast-moving items", body: "Use top-selling product summaries and the low-stock list to spot products that may need closer attention. Compare software records with periodic physical counts to catch mistakes or loss." }],
    faqs: [{ question: "Can different employees use the same shop workspace?", answer: "Yes. The owner can create employee accounts for the shop. Staff can record sales and purchases, while reports remain owner-only." }, { question: "Does DukaSmart replace a barcode till?", answer: "DukaSmart's current workflow is a product picker and sales record; it does not claim barcode scanning or dedicated till hardware support." }],
    related: [{ label: "Sales management", href: "/features/sales-management" }, { label: "Inventory management", href: "/features/inventory-management" }, { label: "General retail workflow", href: "/solutions/general-retail" }],
  },
  {
    slug: "electronics-shops", title: "Sales and stock records for electronics shops", metaTitle: "Electronics Shop Inventory Management Software", description: "Track electronics products, sales, purchase costs, and restocking points in a shared shop management workspace.", intro: "Electronics retailers need clear product records and dependable purchase costs, especially when similar products differ by model or specification. A disciplined catalogue makes counter sales and stock checks easier to reconcile.",
    sections: [{ heading: "Use specific product names", body: "Record model or distinguishing details in product names and categories so staff can select the intended item. DukaSmart tracks product quantities and prices, but it does not currently manage serial numbers, warranties, or device activation." }, { heading: "Connect purchases to inventory", body: "Record supplier deliveries and unit costs as they arrive. Quantities update stock, and the latest cost is stored for future sales; completed sale items retain their historical cost." }, { heading: "Review sales and low stock", body: "Owner summaries show daily and monthly sales, top products, and low-stock items. Use these signals with supplier lead times and physical checks when planning replenishment." }],
    faqs: [{ question: "Does DukaSmart track serial numbers or warranties?", answer: "No. The current product record is quantity-based and does not include serial-number or warranty lifecycle tracking." }, { question: "Can I see which electronics sell most often?", answer: "The owner dashboard summarizes top-selling products for the current month based on recorded sales." }],
    related: [{ label: "Business reports", href: "/features/business-reports" }, { label: "Purchase management", href: "/features/purchase-management" }, { label: "General retail workflow", href: "/solutions/general-retail" }],
  },
  {
    slug: "cosmetics-shops", title: "Keep cosmetics shop stock and sales organized", metaTitle: "Cosmetics Shop Stock Management Software", description: "Organize cosmetics product quantities, selling prices, sales, and low-stock checks with DukaSmart.", intro: "Cosmetics shops often handle many small products, shades, sizes, and repeat purchases. Clear product naming and timely stock records make it easier to answer what is available and what should be reordered.",
    sections: [{ heading: "Make product choices unambiguous", body: "Include relevant product, shade, size, or pack details in names and categories. A clearly maintained product list helps a team avoid confusing similar items at the counter." }, { heading: "Update quantities with sales", body: "Record the item and quantity sold, then let the sale update on-hand stock. Set thresholds for products that need frequent replenishment." }, { heading: "Check your records against shelves", body: "Use the stock list as a working record, and periodically count physical products. Investigate discrepancies, expired items, damaged goods, or unrecorded samples using your shop's own process." }],
    faqs: [{ question: "Can I manage shade and size variants?", answer: "You can distinguish variants by maintaining separate product entries with clear names. DukaSmart does not currently provide a separate variant matrix." }, { question: "Does DukaSmart manage expiry dates?", answer: "Expiry-date tracking is not included in the current product record. Use an additional process for products that require expiry monitoring." }],
    related: [{ label: "Inventory management", href: "/features/inventory-management" }, { label: "Sales management", href: "/features/sales-management" }, { label: "General retail workflow", href: "/solutions/general-retail" }],
  },
  {
    slug: "general-retail", title: "Practical shop management for general retailers", metaTitle: "Retail Shop Management Software for Tanzania", description: "Bring daily sales, product stock, purchases, and owner reports into one simple retail management system.", intro: "Independent retailers need straightforward records that fit the way the shop already works. DukaSmart brings essential product, sales, and restocking workflows together without requiring specialist equipment.",
    sections: [{ heading: "Start with the products you sell", body: "Create product records with category, unit, cost, selling price, quantity, and a low-stock threshold. Begin with the products that matter most at the counter and improve the catalogue over time." }, { heading: "Give owners and staff clear roles", body: "Owners can review reports and manage the shop; employees can record sales and purchases. Individual accounts help keep activity attached to the person using the system." }, { heading: "Review the week and act", body: "Check sales totals, top products, outstanding credit, and items below their threshold. Treat these summaries as prompts for shop decisions and verify important figures against your source records." }],
    faqs: [{ question: "What kind of shop can use DukaSmart?", answer: "It is designed for small retail shops that need quantity-based product, sale, purchase, and reporting workflows." }, { question: "Do I need a special device?", answer: "No special device is required. Use a modern web browser on a phone, tablet, or computer." }],
    related: [{ label: "Sales management", href: "/features/sales-management" }, { label: "Inventory management", href: "/features/inventory-management" }, { label: "Mini supermarket workflow", href: "/solutions/mini-supermarkets" }],
  },
];

export const articles: Article[] = [
  {
    slug: "manage-stock-in-a-small-shop-tanzania", category: "Inventory basics", published: "2026-09-30", title: "How to Manage Stock in a Small Shop in Tanzania", metaTitle: "How to Manage Stock in a Small Shop in Tanzania", description: "A practical routine for organizing products, recording stock movement, setting reorder points, and checking inventory in a Tanzanian shop.", intro: "Good stock control is a repeatable routine, not a once-a-year stocktake. A few simple habits can help a small shop know what it owns, what is moving, and what needs attention next.",
    sections: [{ heading: "Start with a usable product list", body: "Give every sellable item a clear, consistent name. Record its unit, cost, selling price, and opening quantity. If two items look similar, include the detail that helps staff distinguish them at the counter, such as size, brand, or pack." }, { heading: "Record every movement promptly", body: "Sales reduce stock; deliveries increase it. Record returns, damaged goods, samples, and personal use through a consistent adjustment process too. If a movement is written down later, memory can easily miss a product or quantity." }, { heading: "Set reorder points based on real lead time", body: "A useful reorder point considers how quickly an item sells while you wait for replenishment, plus a modest buffer for uncertainty. Review the threshold when sales patterns or supplier delivery times change." }, { heading: "Count high-impact items regularly", body: "Count fast-moving, high-value, or frequently disputed products more often than slow movers. Compare the count with the record, investigate the difference, and correct the underlying process rather than only changing the number." }, { heading: "Use a digital record when it saves work", body: "A shared inventory tool can link sales and purchases to stock counts and flag items below a chosen threshold. DukaSmart provides those workflows for small retailers; it remains important to keep product names accurate and conduct physical checks." }],
    faqs: [{ question: "How often should a small shop count stock?", answer: "There is no single interval for every shop. Count fast-moving or valuable items more often, and set a routine that your team can maintain." }, { question: "What is the most important first step?", answer: "Begin with a clean list of products and units, then record stock movement consistently." }],
    related: [{ label: "Inventory management in DukaSmart", href: "/features/inventory-management" }, { label: "Stock reorder calculator", href: "/tools/stock-calculator" }, { label: "Hardware shop workflow", href: "/solutions/hardware-shops" }],
  },
  {
    slug: "common-stock-management-problems-tanzania", category: "Inventory basics", published: "2026-09-30", title: "5 Common Stock Management Problems Facing Tanzanian Shop Owners", metaTitle: "5 Stock Management Problems for Tanzanian Shops", description: "Learn why stock records drift, how late reordering and unclear product names create problems, and practical ways to improve a small shop's routine.", intro: "Stock problems often appear as missing products or empty shelves, but the cause may be a weak process: late updates, unclear units, informal credit, or purchases that never make it into the record.",
    sections: [{ heading: "1. Sales are recorded after the rush", body: "When sales are entered at closing time, individual items and quantities are easier to forget. Record transactions at the counter where possible and make the workflow short enough that staff will use it." }, { heading: "2. Similar products have confusing names", body: "A list with vague names invites selection mistakes. Include brand, size, colour, or pack details when they distinguish one item from another." }, { heading: "3. Reordering starts only after a product runs out", body: "Set a low-stock trigger that accounts for sales during supplier lead time. Check it routinely and adjust it as demand changes." }, { heading: "4. Deliveries and damaged items are not reconciled", body: "Count received quantities against supplier documents. Record shortages, damage, and returns with a consistent note so the shop's on-hand number reflects what can actually be sold." }, { heading: "5. No one owns the stock routine", body: "Agree who records sales, who enters purchases, and who investigates count differences. A named owner for each step makes missing records visible and correctable." }, { heading: "Make the routine easier to repeat", body: "A connected sales and inventory tool can reduce duplicate entry by updating quantities when sales and purchases are recorded. DukaSmart supports these core workflows, while physical counts and good staff habits remain essential." }],
    faqs: [{ question: "Can software eliminate stock loss?", answer: "No. It can make recorded activity and discrepancies easier to review, but it cannot replace secure handling, receiving checks, and physical counts." }, { question: "Which problem should I solve first?", answer: "Start with the source of the biggest recurring difference, often late sales entry or unrecorded deliveries." }],
    related: [{ label: "Stock management system", href: "/features/inventory-management" }, { label: "Purchase tracking", href: "/features/purchase-management" }, { label: "How to prevent stock loss", href: "/blog/prevent-stock-loss-retail-shop" }],
  },
  {
    slug: "manual-stock-book-vs-digital-inventory", category: "Tools and methods", published: "2026-09-30", title: "Manual Stock Book vs Digital Inventory Management", metaTitle: "Manual Stock Book vs Digital Inventory for Shops", description: "Compare the strengths and trade-offs of a paper stock book and digital inventory system for a small retail business.", intro: "Paper and digital records can both support a shop. The right choice depends on how many products move, how many people need the information, and how reliably the routine is followed.",
    sections: [{ heading: "Where a paper book works well", body: "A notebook is inexpensive, works without internet, and is familiar to many teams. For a small catalogue with few transactions, a clearly maintained book may be enough." }, { heading: "Where paper becomes harder to maintain", body: "Finding a transaction, totaling a period, or sharing a current count can take time. Separate notebooks for sales, stock, and purchases may drift apart, especially when updates are delayed." }, { heading: "What a digital system can improve", body: "A shared system can connect sales and purchase records to quantities, make low-stock items easier to find, and summarize activity. DukaSmart is browser-based and supports owner and employee roles for these day-to-day tasks." }, { heading: "What digital tools do not solve by themselves", body: "A system is only as useful as the data entered. It does not replace physical counts, staff training, supplier checks, backups, or a fallback routine during a connectivity outage." }, { heading: "Choose with a short trial", body: "List the recurring task that consumes the most time or causes the most errors. Test whether the tool makes that task simpler for the people who will use it, and keep an export or backup plan for important records." }],
    faqs: [{ question: "Should a small shop stop using paper completely?", answer: "Not necessarily. Some shops keep paper as a temporary outage or receiving record while maintaining one digital source of truth." }, { question: "Does DukaSmart work offline?", answer: "DukaSmart is a web application and requires an internet connection to use its live shop workflows." }],
    related: [{ label: "Inventory management", href: "/features/inventory-management" }, { label: "Digitizing a small shop", href: "/blog/digitize-a-small-shop-tanzania" }, { label: "About DukaSmart", href: "/about" }],
  },
  {
    slug: "calculate-profit-small-shop", category: "Business basics", published: "2026-09-30", title: "How to Calculate Profit in a Small Shop", metaTitle: "How to Calculate Profit in a Small Shop", description: "Understand sales revenue, cost of goods sold, gross profit, and operating expenses with a simple example for a small retailer.", intro: "A sales total is not the same as profit. To understand what a shop earned, separate the money received from the cost of the items sold and the other expenses of running the business.",
    sections: [{ heading: "Calculate sales revenue", body: "Add the selling price of each item sold during the period. For example, selling 10 items at TZS 8,000 each gives TZS 80,000 in revenue before considering cost or expenses." }, { heading: "Subtract the cost of the items sold", body: "If each of those 10 items cost TZS 5,000 to buy, the cost of goods sold is TZS 50,000. Gross profit is TZS 80,000 minus TZS 50,000, or TZS 30,000." }, { heading: "Account for operating expenses", body: "Rent, wages, transport, utilities, taxes, fees, and other costs reduce the amount left after gross profit. Net profit requires including the relevant expenses for the same period." }, { heading: "Keep costs tied to the right sale", body: "When purchase prices change, avoid applying today's cost to every historical sale. Keep a dated record of costs or use a system that freezes item cost when a sale is made. DukaSmart's estimated profit uses the cost and selling price stored on sale items." }, { heading: "Try the simple calculator", body: "Use the profit calculator to estimate gross profit and gross margin from total sales and cost of goods sold. It is an educational estimate, not an accounting or tax statement." }],
    faqs: [{ question: "What is the difference between gross and net profit?", answer: "Gross profit subtracts product cost from sales revenue. Net profit also accounts for operating expenses and other relevant costs." }, { question: "Does the DukaSmart report show net profit?", answer: "No. It shows estimated product gross profit before operating expenses, taxes, and other costs." }],
    related: [{ label: "Profit calculator", href: "/tools/profit-calculator" }, { label: "Business reports", href: "/features/business-reports" }, { label: "Sales management", href: "/features/sales-management" }],
  },
  {
    slug: "track-credit-sales-in-a-duka", category: "Sales and customers", published: "2026-09-30", title: "How to Track Credit Sales in a Duka", metaTitle: "How to Track Credit Sales in a Duka", description: "Set a consistent process for recording customer credit, reviewing outstanding balances, and protecting customer information in a small shop.", intro: "Credit sales can help maintain customer relationships, but unclear records make follow-up uncomfortable for both the shop and the customer. A consistent, respectful record is the foundation of a useful process.",
    sections: [{ heading: "Agree the terms before recording", body: "Confirm the items, total, expected payment date, and any agreed conditions with the customer. Do not rely on memory or an unspoken assumption about when payment is due." }, { heading: "Record the transaction immediately", body: "Mark the sale as credit and record only the customer details needed to identify the transaction. Give the customer a clear receipt or written confirmation through your usual process." }, { heading: "Review balances on a routine", body: "Choose a regular time to review outstanding credit and contact customers politely using the terms you agreed. Update your records when payment is received and retain the transaction history according to your business needs." }, { heading: "Protect personal details", body: "Limit access to customer information, avoid sharing debt lists publicly, and collect only details that serve a clear business purpose. Follow applicable privacy and consumer rules." }, { heading: "Use a sales record that distinguishes credit", body: "DukaSmart lets the team mark a sale as paid or credit and optionally store a name and phone number. Owner reports summarize outstanding credit; collection and reminders are still handled by the shop." }],
    faqs: [{ question: "Does the app message customers about overdue credit?", answer: "No. DukaSmart records credit sales and summaries but does not send automatic reminders or collect payments." }, { question: "Should I record every customer's phone number?", answer: "Only collect details you need, explain how they will be used, and protect access to them." }],
    related: [{ label: "Credit sales feature", href: "/features/credit-sales" }, { label: "Business reports", href: "/features/business-reports" }, { label: "Sales management", href: "/features/sales-management" }],
  },
  {
    slug: "prevent-stock-loss-retail-shop", category: "Inventory basics", published: "2026-09-30", title: "How to Prevent Stock Loss in a Retail Shop", metaTitle: "How to Prevent Stock Loss in a Retail Shop", description: "Practical receiving, counting, access, and record-keeping habits that help small retailers identify and reduce avoidable stock loss.", intro: "Stock loss can come from receiving mistakes, damage, expired goods, recording errors, or theft. Better visibility begins with a process that makes each movement accountable without making everyday work unmanageable.",
    sections: [{ heading: "Check deliveries as they arrive", body: "Compare delivered quantities and condition with the supplier's note before shelving goods. Record shortages and damage promptly so the stock figure starts from what was actually received." }, { heading: "Separate duties where practical", body: "For higher-risk stock, have a second person verify receiving or periodic counts when staffing allows. Keep access and adjustment responsibilities clear." }, { heading: "Count strategically and investigate", body: "Schedule regular counts for valuable and fast-moving products. When numbers differ, review recent sales, purchases, returns, damage, and adjustments to find the cause." }, { heading: "Record all stock movement", body: "A stock count cannot explain a discrepancy on its own. Record sales, received purchases, returns, damaged items, and other adjustments close to when they happen." }, { heading: "Use alerts as an early signal", body: "Low-stock alerts can help identify a product that is selling faster than expected or has not been replenished. They are a prompt to investigate, not proof of loss." }],
    faqs: [{ question: "Can inventory software prevent theft?", answer: "No software can guarantee that. Clear access, receiving checks, physical counts, and timely records can help surface suspicious or accidental differences." }, { question: "How often should I investigate a stock mismatch?", answer: "Investigate promptly while recent delivery, sale, or adjustment details are still easy for the team to confirm." }],
    related: [{ label: "Inventory management", href: "/features/inventory-management" }, { label: "Common stock problems", href: "/blog/common-stock-management-problems-tanzania" }, { label: "Purchase tracking", href: "/features/purchase-management" }],
  },
  {
    slug: "pos-vs-inventory-management-system", category: "Tools and methods", published: "2026-09-30", title: "POS vs Inventory Management System: What Is the Difference?", metaTitle: "POS vs Inventory Management System for Small Shops", description: "Learn how point-of-sale tools differ from inventory systems and what a small retailer should look for in connected sales and stock workflows.", intro: "A point-of-sale system focuses on completing transactions. An inventory system focuses on the products a business owns. Many shops need the two activities to share data, but they are not identical tools.",
    sections: [{ heading: "What a POS system usually does", body: "A POS workflow records a checkout, payment, and often a receipt. Some systems also support barcode scanners, cash drawers, payment terminals, and detailed tax workflows." }, { heading: "What inventory management covers", body: "Inventory tools maintain product records, quantities, costs, and replenishment signals. They help owners understand stock on hand and track movement into and out of the shop." }, { heading: "Why connected records matter", body: "If a sale does not reduce inventory, the product count can become stale. If a purchase is not entered, the system may report less stock than the shop received. Linking these records reduces duplicate work." }, { heading: "Check the details before choosing", body: "Ask whether the system supports your payment methods, hardware, taxes, offline needs, product variants, supplier workflow, exports, and staff roles. DukaSmart currently provides browser-based sales, quantity-based stock, purchases, and reports; it is not a payment terminal or barcode till." }, { heading: "Choose for the workflow you have", body: "A small retailer may need a simple connected sales-and-stock record more than a full POS installation. Trial the real counter workflow with the staff who will use it before moving business records." }],
    faqs: [{ question: "Is DukaSmart a POS system?", answer: "It includes a browser-based sales recording workflow connected to stock. It does not currently include payment-terminal or barcode-scanner integrations." }, { question: "Can POS and inventory software be used together?", answer: "Yes, if their integrations keep product, sales, and payment records consistent and avoid duplicate entry." }],
    related: [{ label: "Sales management", href: "/features/sales-management" }, { label: "Inventory management", href: "/features/inventory-management" }, { label: "Manual vs digital stock records", href: "/blog/manual-stock-book-vs-digital-inventory" }],
  },
  {
    slug: "digitize-a-small-shop-tanzania", category: "Getting started", published: "2026-09-30", title: "How to Start Digitizing a Small Shop in Tanzania", metaTitle: "How to Digitize a Small Shop in Tanzania", description: "A low-friction plan for moving a small shop's product list, sales, purchases, and team routines into digital records.", intro: "Digitizing a shop does not mean changing every process at once. Start with one repeated problem, test a small workflow, and keep a safe copy of the information that matters.",
    sections: [{ heading: "Choose one problem to solve first", body: "Pick the task that currently causes the most repeated work: checking stock, finding sales totals, or recording purchases. A clear first goal helps you judge whether a tool is useful." }, { heading: "Clean a small product list", body: "Start with the items your team sells most often. Agree on product names and units, check prices and quantities, and note any uncertain opening balances before importing or entering records." }, { heading: "Train the people who will use it", body: "Walk through a real sale and a real delivery with the owner and staff. Decide who enters each activity, when it should be entered, and how to handle internet or device interruptions." }, { heading: "Keep access and data responsibilities clear", body: "Use individual accounts, give each person only the access needed for their role, and avoid sharing passwords. Understand how the provider stores data and what export or backup options are available." }, { heading: "Review after the first few weeks", body: "Compare digital records with physical stock and the shop's existing notes. Gather staff feedback, fix confusing product names, and expand only after the first workflow is dependable." }, { heading: "Start with connected essentials", body: "DukaSmart brings product stock, sales, purchases, and owner reports into a browser-based workspace for small retailers. You can create an account and begin with the product records most important to your shop." }],
    faqs: [{ question: "Do I need a computer to digitize my shop?", answer: "Not always. Many browser-based tools work on a modern smartphone, although a larger screen can make some tasks easier." }, { question: "Should I enter every product on day one?", answer: "Start with a checked, manageable set of products and build the catalogue in stages if a full stocktake would slow the shop down." }],
    related: [{ label: "General retail solution", href: "/solutions/general-retail" }, { label: "Inventory management", href: "/features/inventory-management" }, { label: "About DukaSmart", href: "/about" }],
  },
];